copy "src\scripts\DSDifyer.pas" "dist\DSDifyer\Edit Scripts\DSDifyer.pas"
copy "src\scripts\ESP-to-DSD.py" "dist\DSDifyer\ESP-to-DSD.py"
copy "src\scripts\Generate-Folders.py" "dist\DSDifyer\Generate-Folders.py"
copy "src\scripts\xEdit-to-DSD.py" "dist\DSDifyer\xEdit-to-DSD.py"
copy "src\scripts\xTranslator-to-DSD.py" "dist\DSDifyer\xTranslator-to-DSD.py"
copy "LICENSE.txt" "dist\DSDifyer\LICENSE.txt"
